default = "hhuOS"
timeout = 0
log_level = "info"

[entries]
  [entries.hhuOS]
    name = "hhuOS"
    image = "\\hhuOS.bin"
    argv = "log_level=debug log_com_port=COM1"
    modules = [ { image = "\\hhuOS.initrd", argv = "initrd" } ]
